# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBfM_yv7mvOqq36PwQUjK-oP0c5w1LRZ
"""

import pandas as pd
df = pd.read_csv("Nat_Gas.csv")
print(df.columns)
print(df.head())
print("Total rows:", len(df))
print("Missing values:", df.isnull().sum())

import matplotlib.pyplot as plt

#converting date column into proper date format
df["Dates"] = pd.to_datetime(df["Dates"])

#plotting graph
plt.figure(figsize=(12, 5))
plt.plot(df["Dates"],df["Prices"],
         marker='o', color='royalblue')
plt.title("Natural Gas Prices Over Time")
plt.xlabel("Date")
plt.ylabel("Price ($/MMBtu)")
plt.grid(True)
plt.show()

#finding month from date
df["Month"] = df["Dates"].dt.month

#average price each month
monthly_avg = df.groupby("Month")["Prices"].mean()

#Bar Chart
plt.figure(figsize=(10, 5))
monthly_avg.plot(kind='bar', color='mediumpurple')

plt.title("Average Price by Month")
plt.xlabel("Month (1=Jan, 12=Dec)")
plt.ylabel("Avg Price ($/MMBtu)")
plt.grid(True)
plt.show()

import numpy as np
from scipy.optimize import curve_fit

# calculating date from reference date
start_date = df["Dates"].min()
df["t"] = (df["Dates"] - start_date).dt.days

# defining seasonal model
def seasonal_model(t, A, omega, phi, B, C):
    return A * np.sin(omega * t + phi) + B * t + C

# Model fit karo
params, _ = curve_fit(
    seasonal_model,
    df["t"], df["Prices"],
    p0=[1.5, 2*np.pi/365, 0, 0.001, 3.0],
    maxfev=10000
)

print("Model fitting Done ✅")
print("Parameters:", params)

from datetime import datetime

def estimate_price(date_string):
    # Date convert karo
    input_date = datetime.strptime(date_string, "%Y-%m-%d")

    # Days calculate karo
    t_val = (input_date - start_date.to_pydatetime()).days

    # Model se price nikalo
    price = seasonal_model(t_val, *params)

    return round(price, 4)

# Testing!
print(estimate_price("2025-01-15"))  # Future price
print(estimate_price("2022-08-01"))  # Past price

# creating past 1 year dates
future_dates = pd.date_range(
    start="2024-10-01",
    end="2025-09-30",
    freq="D"
)

future_t = [(d - start_date).days for d in future_dates]
future_prices = [seasonal_model(t, *params) for t in future_t]

# Final graph
plt.figure(figsize=(14, 6))

# Historical data
plt.scatter(df["Dates"], df["Prices"],
            color='steelblue', label='Actual Data', zorder=5)

# Fitted curve
fitted = seasonal_model(df["t"], *params)
plt.plot(df["Dates"], fitted,
         color='mediumseagreen', label='Fitted Curve')

# Future extrapolation
plt.plot(future_dates, future_prices,
         color='tomato', linestyle='--', label='Future Estimate')

plt.title("Natural Gas Price — Historical + Future Forecast")
plt.xlabel("Date")
plt.ylabel("Price ($/MMBtu)")
plt.legend()
plt.grid(True)
plt.show()